name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4.1.0
      with:
        python-version: 3.9
    - name: Attempt to use cached dependencies
      id: cache-python
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-dev.txt') }}-${{ github.actor == 'dependabot' }}
    - name: Installing dependencies
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: pip install -r requirements-dev.txt
    - name: Setup environment variables
      run: cp .env.example .env
    - name: Running pytest
      run: pytest --color=yes

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4.1.0
      with:
        python-version: 3.9
    - name: Attempt to use cached dependencies
      id: cache-python
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-dev.txt') }}-${{ github.actor == 'dependabot' }}
    - name: Installing dependencies
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: pip install -r requirements-dev.txt
    - name: Setup environment variables
      run: cp .env.example .env
    - name: Getting coverage report
      run: coverage run -m pytest && coverage xml
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
