name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v3.1.0
      with:
        python-version: 3.9
    - name: Attempt to use cached dependencies
      id: cache-python
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-dev.txt') }}-${{ github.actor == 'dependabot' }}
    - name: Installing dependencies
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: pip install -r requirements-dev.txt
    - name: Setup environment variables
      run: cp .env.example .env
    - name: Running pylint
      run: pylint serverctl/ tests/ -v

  isort:
    runs-on: ubuntu-latest
    needs: pylint
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v3.1.0
      with:
        python-version: 3.9
    - name: Attempt to use cached dependencies
      id: cache-python
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-dev.txt') }}-${{ github.actor == 'dependabot' }}
    - name: Installing dependencies
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: pip install -r requirements-dev.txt
    - name: Running isort
      run: isort .

  mypy:
    runs-on: ubuntu-latest
    needs: isort
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v3.1.0
      with:
        python-version: 3.9
    - name: Attempt to use cached dependencies
      id: cache-python
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-dev.txt') }}-${{ github.actor == 'dependabot' }}
    - name: Installing dependencies
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: pip install -r requirements-dev.txt
    - name: Running mypy
      run: mypy .
      env:
        MYPY_FORCE_COLOR: 1
        TERM: xterm-color
